name: Quick Windows Build

on:
  workflow_dispatch: # Manual trigger only
  push:
    branches: [main]
    paths:
      - "main.py"
      - "requirements.txt"
      - ".github/workflows/quick-windows-build.yml"

jobs:
  quick-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name "YouTube_MP3_Downloader" --optimize=2 --strip main.py

      - name: Test executable
        run: |
          # Basic test to ensure executable was created
          if (Test-Path "dist\YouTube_MP3_Downloader.exe") {
            Write-Host "✅ Executable created successfully!"
            $file = Get-Item "dist\YouTube_MP3_Downloader.exe"
            Write-Host "📁 File size: $([math]::Round($file.Length / 1MB, 2)) MB"
          } else {
            Write-Error "❌ Executable not found!"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: YouTube_MP3_Downloader_Windows_Quick
          path: dist/YouTube_MP3_Downloader.exe
          retention-days: 7
